# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.IntegerField()),
                ('validade', models.DateField()),
                ('tipo', models.CharField(max_length=120)),
                ('familia', models.CharField(max_length=120)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
